sudo: false
language: php
php:
  - 7.1

matrix:
  fast_finish: true

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer install --prefer-dist

script:
  - ./vendor/bin/phpcs
